platform:
  - x64

init:
  - ps: Disable-NetFirewallRule -DisplayName 'Core Networking - Group Policy (LSASS-Out)'

environment:
  RUST_INSTALL_DIR: C:\Rust
  matrix:
    - RUST_INSTALL_TRIPLE: i686-pc-windows-msvc
      RUST_VERSION: 1.20.0
    - RUST_INSTALL_TRIPLE: i686-pc-windows-msvc
      RUST_VERSION: beta
    - RUST_INSTALL_TRIPLE: i686-pc-windows-msvc
      RUST_VERSION: nightly
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: 1.20.0
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: beta
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: nightly
    - RUST_INSTALL_TRIPLE: i686-pc-windows-gnu
      RUST_VERSION: 1.20.0
    - RUST_INSTALL_TRIPLE: i686-pc-windows-gnu
      RUST_VERSION: beta
    - RUST_INSTALL_TRIPLE: i686-pc-windows-gnu
      RUST_VERSION: nightly
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-gnu
      RUST_VERSION: 1.20.0
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-gnu
      RUST_VERSION: beta
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-gnu
      RUST_VERSION: nightly

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:RUST_INSTALL_TRIPLE}.exe"
  - cmd: rust-%RUST_VERSION%-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /DIR="%RUST_INSTALL_DIR%"
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin
  - rustc --version
  - cargo --version

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
